image: kasproject/kas:0.13.0

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1

stages:
- build
#- deploy
# TODO: deploy artifacts to S3 and submit LAVA job

build_bbb:
  stage: build
  script:
    - /kas/docker-entrypoint
    - cd poky/
    - gosu builder kas build --target core-image-minimal meta-cip-bbb/kas-bbb.yml
